spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_db
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8080

jwtCookie: bezkoder
jwtSecret: bezKoderSecretKey
jwtExpirationMs: 86400000
